// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeJPLYhW81WGs5Ojf5k51P-sYzAoZkUc4',
    appId: '1:394863329998:web:5084b3691d14282e56c69f',
    messagingSenderId: '394863329998',
    projectId: 'proyectopsicologia-23e96',
    authDomain: 'proyectopsicologia-23e96.firebaseapp.com',
    storageBucket: 'proyectopsicologia-23e96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAayVf9uzbccEkjxsf7kdPNOGBux_n-7Ko',
    appId: '1:394863329998:android:13839d3810e2f6f756c69f',
    messagingSenderId: '394863329998',
    projectId: 'proyectopsicologia-23e96',
    storageBucket: 'proyectopsicologia-23e96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt9MoLrrNrU3RIdSDVg_lSeRlY73FdTyY',
    appId: '1:394863329998:ios:1f3e39b29eedee6956c69f',
    messagingSenderId: '394863329998',
    projectId: 'proyectopsicologia-23e96',
    storageBucket: 'proyectopsicologia-23e96.appspot.com',
    iosBundleId: 'com.example.proyectoPsicologia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt9MoLrrNrU3RIdSDVg_lSeRlY73FdTyY',
    appId: '1:394863329998:ios:dba57d593ae5872456c69f',
    messagingSenderId: '394863329998',
    projectId: 'proyectopsicologia-23e96',
    storageBucket: 'proyectopsicologia-23e96.appspot.com',
    iosBundleId: 'com.example.proyectoPsicologia.RunnerTests',
  );
}
